gems:
  - jekyll-mentions
  - jekyll-sitemap

footer-links:
  github: nicolasbock

pages_list:
  Main: "/technical-reports"

url: http://www.freeon.org/technical-reports
baseurl: "/technical-reports"
