gems:
  - jekyll-mentions
  - jekyll-sitemap

footer-links:
  github: nicolasbock

pages_list:
  Main: "/technical-reports"

permalink: none

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

url: http://www.freeon.org/technical-reports
baseurl: "/technical-reports"
